HOST: http://www.google.com/

--- Core Identity API ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Organization Management Resources
The following is a section of resources related to the Organization management. An organization is the root model.
--

Create a new organization
POST /organizations
> Content-Type: application/json
{
    "name":"sample-org",
    "description":"This is a sample organization",
    "administrators":
    [
        {
            "emailAddress":"admin@example.com",
            "username":"admin1",
            "password":"password"
        }
    ]
}
< 201
< Content-Type: application/json
< Location: /organizations/1234-1234-1234-1234
{}

List organizations that you have access to.
GET /organizations
< 200
< Content-Type: application/json
[
{}
]

Get an organization
GET /organizations/{id}
< 200
< Content-Type: application/json
[
{}
]

Update an organization
PUT /organizations/{id}
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 200
< Content-Type: application/json
[
{}
]

Delete an organization
DELETE /organizations/{id}
< 204

-- Payment Resources --

This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }