HOST: http://www.google.com/

--- Core Identity API ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Organization Management Resources
The following is a section of resources related to the Organization management. An organization is the root model.
--

Create a new organization.
POST /organizations
> Content-Type: application/json
{
    "name":"sample-org",
    "description":"This is a sample organization",
    "administrators":
    [
        {
            "emailAddress":"admin@example.com",
            "username":"admin1",
            "password":"password"
        }
    ]
}
< 201
< Content-Type: application/json
< Location: /organizations/1234-1234-1234-1234
{
    "uuid":"1234-1234-1234-1234",
    "name":"sample-org,
    "description":"This is a sample organization",
    "administratorIds":["1234-1234-1234-1234"]
}

List organizations that you have access to.
GET /organizations
< 200
< Content-Type: application/json
[]

Read an organization by uuid or name.
GET /organizations/{uuid|name}
< 200
< Content-Type: application/json
[]

Update an organization by uuid or name.
PUT /organizations/{uuid|name}
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 204

Delete an organization by uuid or name.
DELETE /organizations/{uuid|name}
< 204

--
Application Management Resources
--

Create an application within an organization.
POST /organizations/{uuid|name}/applications
> Content-type: application/json
{
    "name":"sample-application",
    "description":"Sample application description"
}
< 201
< Content-Type: application/json
< Location: /applications/{uuid}
{
    "uuid":"1234-1234-1234-1234",
    "organizationId":"1234-1234-1234-1234",
    "name":"sample-application",
    "description":"Sample application description"
}

List applications within an organization.
GET /organizations/{uuid|name}/applications
< 200
< Content-Type: application/json
[
    {
        "uuid":"1234-1234-1234-1234",
        "organizationId":"1234-1234-1234-1234",
        "name":"sample-application",
        "description":"Sample application description"
    }
]

Read an application by name or uuid.
GET /organizations/{uuid|name}/applications/{uuid|name}
< 200
< Content-Type: application/json
{
    "uuid":"1234-1234-1234-1234",
    "organizationId":"1234-1234-1234-1234",
    "name":"sample-application",
    "description":"Sample application description"
}

Read an application by uuid.
GET /applications/{uuid}
< 200
< Content-Type: application/json
{
    "uuid":"1234-1234-1234-1234",
    "organizationId":"1234-1234-1234-1234",
    "name":"sample-application",
    "description":"Sample application description"
}

--
User Management Resources
--

This resource allows you to submit payment information to process your *shopping cart* items
POST /organizations/{uuid|name}/applications/{uuid|name}/users
> Content-Type: application/json
{
    "emailAddress": "user@example.com",
    "username": "user1",
    "password": "password"
}
< 201
< Content-Type: application/json
< Location: /users/{uuid}
{ "receipt": "/payment/receipt/1" }